version: "3.7"

x-museum_build_config: &museum_build_config
  context: ./src
  dockerfile: ../Dockerfile
  args:
    - GO_VERSION=1.19
    - ALPINE_VERSION=3.16

services:
  # TODO: delete this service in the future
  yq:
    image: mikefarah/yq:4.27.2
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: yq

  museum_dev:
    build:
      <<: *museum_build_config
      target: dev
    working_dir: /workspace
    volumes:
      - ./src:/workspace

  museum:
    build:
      <<: *museum_build_config
      target: prod
    working_dir: /workspace
    entrypoint: /museum deploy
