version: "3.7"

x-museum_build_config: &museum_build_config
  context: ./src
  dockerfile: ../Dockerfile
  args:
    - GO_VERSION=1.19
    - DEBIAN_VERSION=11-slim

services:
  museum_dev:
    build:
      <<: *museum_build_config
      target: dev
    working_dir: /workspace
    volumes:
      - .:/workspace

  museum:
    build:
      <<: *museum_build_config
      target: prod
    working_dir: /workspace
    volumes:
      - ${PWD}:/workspace
    entrypoint: /museum
